export const PSF_AUTHORITY_OVERLAY = {
  primary: [
    "ctahr.hawaii.edu",
    "plants.usda.gov",
    "edis.ifas.ufl.edu",
    "ecoport.org",
    "breadfruitinstitute.org",
    "ntbg.org",
  ],
  community: [
    "reddit.com",
    "permies.com",
    "tropicalfruitforum.com",
    "houzz.com",
    "gardenweb.com",
  ],
  reference: [
    "wikipedia.org",
    "powo.science.kew.org",
    "ecoCrop.fao.org",
  ],
  secondary: [
    "gardeningknowhow.com",
    "thespruce.com",
    "bhg.com",
    "miraclegro.com",
    "pennington.com",
    "allaboutgardening.com",
  ],
  excluded: [
    "arxiv.org",
    "huggingface.co",
    "github.com/trending",
    "venturebeat.com",
    "techcrunch.com",
    "the-decoder.com",
    "simonwillison.net",
    "openai.com",
    "anthropic.com",
    "deepmind.google",
    "ai.meta.com",
    "microsoft.com/en-us/research",
    "bloomberg.com",
    "wsj.com",
    "nytimes.com",
    "washingtonpost.com",
    "ft.com",
    "economist.com",
    "forbes.com",
    "businessinsider.com",
    "cnbc.com",
    "axios.com",
    "theverge.com",
    "arstechnica.com",
    "wired.com",
    "substack.com",
  ],
};
